[package]
name = "mmrecode-render"
description = "Codec-independent render planning and execution for MMRecode"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
mpeg2 = ["dep:mmrecode-mpeg2"]
mpegts = ["mpeg2", "dep:mmrecode-mpegaudio", "dep:mmrecode-mpegts"]
h264 = ["dep:mmrecode-h264", "dep:mmrecode-isobmff"]
mmfx = ["dep:mmrecode-mmfx"]

[dependencies]
image.workspace = true
mmrecode-core.workspace = true
mmrecode-edit.workspace = true
mmrecode-h264 = { workspace = true, optional = true }
mmrecode-isobmff = { workspace = true, optional = true }
mmrecode-mpegaudio = { workspace = true, optional = true }
mmrecode-mpeg2 = { workspace = true, optional = true }
mmrecode-mpegts = { workspace = true, optional = true }
mmrecode-mmfx = { workspace = true, optional = true }

[dev-dependencies]
mmrecode-dv.workspace = true
mmrecode-mjpeg.workspace = true
mmrecode-mpegaudio.workspace = true
mmrecode-mpeg2.workspace = true
mmrecode-mpegts.workspace = true

[lints]
workspace = true
