//! MPEG-2 Video and Layer II render delivery to MPEG-TS.

use std::cmp::Ordering;

use mmrecode_core::{
    CodecDescriptor, CodecId, Error, MediaType, Muxer, Packet, PacketFlags, Rational, Result,
    StreamDescriptor, StreamId, Timestamp, TimestampRounding,
};
use mmrecode_mpegaudio::parse_layer2_stream;
use mmrecode_mpegts::{MpegTsMuxConfig, MpegTsMuxer, SYSTEM_CLOCK_FREQUENCY, TS_PACKET_SIZE};

use crate::RenderPlan;

/// How complete audio frames are selected at the video program end.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum AudioBoundaryPolicy {
    /// Require the selected audio to end at exactly the same rational time as the video.
    Exact,
    /// Keep only complete audio frames whose end does not pass the video end.
    Contained,
    /// Keep complete audio frames whose start precedes the video end.
    Cover,
}

/// A complete MPEG-1 Audio Layer II elementary stream and its timeline start.
#[derive(Clone, Copy, Debug)]
pub struct Layer2AudioInput<'a> {
    /// Complete, frame-aligned Layer II elementary-stream bytes.
    pub data: &'a [u8],
    /// Presentation time of the first audio frame.
    pub start: Timestamp,
}

/// Options for MPEG-2/Layer II MPEG-TS delivery.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MpegTsRenderOptions {
    /// Deterministic program and PID configuration.
    pub mux: MpegTsMuxConfig,
    /// Complete-frame selection rule at the video end.
    pub audio_boundary: AudioBoundaryPolicy,
}

impl Default for MpegTsRenderOptions {
    fn default() -> Self {
        Self {
            mux: MpegTsMuxConfig::default(),
            audio_boundary: AudioBoundaryPolicy::Exact,
        }
    }
}

/// Inspectable accounting for one MPEG-TS render delivery.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MpegTsRenderReport {
    /// MPEG-2 packets copied by the render plan.
    pub copied_video_packets: usize,
    /// MPEG-2 packets regenerated by the render plan.
    pub regenerated_video_packets: usize,
    /// Total MPEG-2 elementary-stream payload bytes.
    pub video_bytes: usize,
    /// Exclusive presentation end of video.
    pub video_end: Timestamp,
    /// Complete Layer II frames available in the input.
    pub available_audio_frames: usize,
    /// Complete Layer II frames selected by the boundary policy.
    pub selected_audio_frames: usize,
    /// Selected Layer II elementary-stream payload bytes.
    pub audio_bytes: usize,
    /// Exclusive presentation end of selected audio, when audio was supplied.
    pub audio_end: Option<Timestamp>,
    /// Selected audio end minus video end, rounded to the nearest microsecond.
    pub av_end_delta_micros: Option<i64>,
    /// Boundary policy used to select audio.
    pub audio_boundary: AudioBoundaryPolicy,
    /// Physical 188-byte TS packets after execution; absent for a dry run.
    pub transport_packets: Option<usize>,
}

impl MpegTsRenderReport {
    /// Returns a compact explanation suitable for a terminal dry run.
    #[must_use]
    pub fn explanation(&self) -> String {
        let audio = match (
            self.audio_end,
            self.av_end_delta_micros,
            self.available_audio_frames,
        ) {
            (Some(_), Some(delta), available) => format!(
                ", audio {}/{} frame(s), end delta {delta:+} us ({:?})",
                self.selected_audio_frames, available, self.audio_boundary
            ),
            _ => ", no audio".to_owned(),
        };
        let transport = self.transport_packets.map_or_else(
            || "dry run".to_owned(),
            |packets| format!("{packets} transport packet(s)"),
        );
        format!(
            "MPEG-TS {transport}: video {} copied + {} regenerated packet(s), {} byte(s){audio}",
            self.copied_video_packets, self.regenerated_video_packets, self.video_bytes
        )
    }
}

/// A validated MPEG-TS delivery plan that has not emitted container bytes yet.
#[derive(Clone, Debug)]
pub struct MpegTsRenderPlan {
    config: MpegTsMuxConfig,
    streams: Vec<StreamDescriptor>,
    packets: Vec<Packet>,
    report: MpegTsRenderReport,
}

impl MpegTsRenderPlan {
    /// Returns the dry-run accounting.
    #[must_use]
    pub const fn report(&self) -> &MpegTsRenderReport {
        &self.report
    }

    /// Returns packets in the order in which the transport muxer will receive them.
    #[must_use]
    pub fn packets(&self) -> &[Packet] {
        &self.packets
    }
}

/// Executed MPEG-TS bytes and final accounting.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MpegTsRenderOutput {
    /// Complete MPEG transport stream.
    pub data: Vec<u8>,
    /// Render and physical-container accounting.
    pub report: MpegTsRenderReport,
}

/// Builds a dry-runnable MPEG-TS delivery plan from executed MPEG-2 render packets.
///
/// Video packets must cover one gap-free, zero-based presentation timeline. Optional Layer II
/// audio is framed without decoding; its end is resolved using [`AudioBoundaryPolicy`] with exact
/// rational comparisons. No transport bytes are generated by this function.
///
/// # Errors
///
/// Returns an error for inconsistent render counts, invalid video timing, malformed Layer II,
/// a non-sample-aligned audio start, or an audio boundary that cannot satisfy the selected policy.
#[allow(clippy::too_many_lines)]
pub fn plan_mpeg2_mpegts(
    render_plan: &RenderPlan,
    video_packets: &[Packet],
    audio: Option<Layer2AudioInput<'_>>,
    options: MpegTsRenderOptions,
) -> Result<MpegTsRenderPlan> {
    let expected_video_packets = render_plan
        .summary
        .copied_packets
        .checked_add(render_plan.summary.encoded_frames)
        .ok_or_else(|| Error::InvalidData("render video packet count overflows".into()))?;
    if video_packets.len() != expected_video_packets {
        return Err(Error::InvalidData(format!(
            "render produced {} video packets but its plan accounts for {expected_video_packets}",
            video_packets.len()
        )));
    }
    let video_end = validate_video_timeline(video_packets)?;
    let video_stream_id = StreamId(u32::from(options.mux.video_pid));
    let audio_stream_id = StreamId(u32::from(options.mux.audio_pid));
    let mut streams = vec![StreamDescriptor {
        id: video_stream_id,
        codec: CodecDescriptor {
            codec_id: CodecId::new("video/mpeg2"),
            codec_tag: None,
            media_type: MediaType::Video,
            configuration: Vec::new(),
        },
        time_base: video_end.time_base,
    }];
    let mut scheduled = Vec::with_capacity(video_packets.len());
    for (index, packet) in video_packets.iter().enumerate() {
        let mut packet = packet.clone();
        packet.stream_id = video_stream_id;
        let order_time = packet.dts.or(packet.pts).ok_or_else(|| {
            Error::InvalidData(format!("video packet {index} has neither DTS nor PTS"))
        })?;
        scheduled.push(ScheduledPacket {
            clock: transport_clock(order_time)?,
            media_order: 0,
            insertion_order: index,
            packet,
        });
    }

    let mut available_audio_frames = 0;
    let mut selected_audio_frames = 0;
    let mut audio_bytes = 0_usize;
    let mut audio_end = None;
    let mut av_end_delta_micros = None;
    if let Some(audio) = audio {
        let frames = parse_layer2_stream(audio.data)?;
        available_audio_frames = frames.len();
        let header = frames[0].header;
        let audio_time_base = Rational::new(1, i64::from(header.sample_rate))?;
        let start = audio
            .start
            .rescale(audio_time_base, TimestampRounding::Exact)?;
        if start.value < 0 {
            return Err(Error::InvalidData(
                "MPEG-TS audio cannot begin at a negative timestamp".into(),
            ));
        }
        let samples_per_frame = i64::from(header.samples_per_frame);
        selected_audio_frames = select_audio_frames(
            frames.len(),
            start,
            samples_per_frame,
            video_end,
            options.audio_boundary,
        )?;
        let selected_samples = i64::try_from(selected_audio_frames)
            .ok()
            .and_then(|count| count.checked_mul(samples_per_frame))
            .ok_or_else(|| Error::InvalidData("selected audio duration overflows".into()))?;
        let end = Timestamp {
            value: start
                .value
                .checked_add(selected_samples)
                .ok_or_else(|| Error::InvalidData("selected audio end overflows".into()))?,
            time_base: audio_time_base,
        };
        audio_end = Some(end);
        av_end_delta_micros = Some(timestamp_delta_micros(end, video_end)?);
        streams.push(StreamDescriptor {
            id: audio_stream_id,
            codec: CodecDescriptor {
                codec_id: CodecId::new("audio/mpeg1"),
                codec_tag: None,
                media_type: MediaType::Audio,
                configuration: Vec::new(),
            },
            time_base: audio_time_base,
        });
        for frame in frames.into_iter().take(selected_audio_frames) {
            let frame_index = i64::try_from(frame.index)
                .map_err(|_| Error::InvalidData("audio frame index does not fit i64".into()))?;
            let pts = Timestamp {
                value: start
                    .value
                    .checked_add(frame_index.checked_mul(samples_per_frame).ok_or_else(|| {
                        Error::InvalidData("audio frame timestamp overflows".into())
                    })?)
                    .ok_or_else(|| Error::InvalidData("audio frame timestamp overflows".into()))?,
                time_base: audio_time_base,
            };
            let data = frame.data(audio.data).to_vec();
            audio_bytes = audio_bytes
                .checked_add(data.len())
                .ok_or_else(|| Error::InvalidData("selected audio byte count overflows".into()))?;
            scheduled.push(ScheduledPacket {
                clock: transport_clock(pts)?,
                media_order: 1,
                insertion_order: frame.index,
                packet: Packet {
                    stream_id: audio_stream_id,
                    data,
                    pts: Some(pts),
                    dts: None,
                    duration: Some(Timestamp {
                        value: samples_per_frame,
                        time_base: audio_time_base,
                    }),
                    flags: PacketFlags::empty(),
                    side_data: Vec::new(),
                },
            });
        }
    }
    scheduled.sort_by_key(|packet| (packet.clock, packet.media_order, packet.insertion_order));
    let video_bytes = video_packets.iter().try_fold(0_usize, |total, packet| {
        total
            .checked_add(packet.data.len())
            .ok_or_else(|| Error::InvalidData("video byte count overflows".into()))
    })?;
    let report = MpegTsRenderReport {
        copied_video_packets: render_plan.summary.copied_packets,
        regenerated_video_packets: render_plan.summary.encoded_frames,
        video_bytes,
        video_end,
        available_audio_frames,
        selected_audio_frames,
        audio_bytes,
        audio_end,
        av_end_delta_micros,
        audio_boundary: options.audio_boundary,
        transport_packets: None,
    };
    Ok(MpegTsRenderPlan {
        config: options.mux,
        streams,
        packets: scheduled
            .into_iter()
            .map(|scheduled| scheduled.packet)
            .collect(),
        report,
    })
}

/// Executes a validated MPEG-TS delivery plan.
///
/// # Errors
///
/// Returns an error if stream registration, packet delivery, or transport finalization fails.
pub fn execute_mpeg2_mpegts(plan: &MpegTsRenderPlan) -> Result<MpegTsRenderOutput> {
    let mut muxer = MpegTsMuxer::with_config(plan.config);
    for descriptor in &plan.streams {
        let expected = descriptor.id;
        let assigned = muxer.add_stream(descriptor.clone())?;
        if assigned != expected {
            return Err(Error::InvalidState(format!(
                "MPEG-TS muxer assigned stream {assigned:?}, expected {expected:?}"
            )));
        }
    }
    for packet in &plan.packets {
        muxer.write_packet(packet.clone())?;
    }
    muxer.finalize()?;
    let data = muxer.into_bytes()?;
    let mut report = plan.report.clone();
    report.transport_packets = Some(data.len() / TS_PACKET_SIZE);
    Ok(MpegTsRenderOutput { data, report })
}

#[derive(Clone, Debug)]
struct ScheduledPacket {
    clock: i64,
    media_order: u8,
    insertion_order: usize,
    packet: Packet,
}

fn validate_video_timeline(packets: &[Packet]) -> Result<Timestamp> {
    let first = packets
        .first()
        .ok_or_else(|| Error::InvalidData("cannot mux an empty MPEG-2 render".into()))?;
    let time_base = first
        .pts
        .ok_or_else(|| Error::InvalidData("video packet 0 has no PTS".into()))?
        .time_base;
    let mut spans = Vec::with_capacity(packets.len());
    for (index, packet) in packets.iter().enumerate() {
        let pts = packet
            .pts
            .ok_or_else(|| Error::InvalidData(format!("video packet {index} has no PTS")))?;
        let duration = packet
            .duration
            .ok_or_else(|| Error::InvalidData(format!("video packet {index} has no duration")))?;
        if pts.time_base != time_base || duration.time_base != time_base {
            return Err(Error::Unsupported(
                "initial MPEG-TS render delivery requires one video time base".into(),
            ));
        }
        if duration.value <= 0 {
            return Err(Error::InvalidData(format!(
                "video packet {index} has a non-positive duration"
            )));
        }
        let end = pts
            .value
            .checked_add(duration.value)
            .ok_or_else(|| Error::InvalidData("video presentation end overflows".into()))?;
        spans.push((pts.value, end));
    }
    spans.sort_unstable();
    let mut cursor = 0_i64;
    for (start, end) in spans {
        if start != cursor {
            return Err(Error::InvalidData(format!(
                "video presentation timeline is not gap-free at timestamp {cursor}"
            )));
        }
        cursor = end;
    }
    Ok(Timestamp {
        value: cursor,
        time_base,
    })
}

fn select_audio_frames(
    available: usize,
    start: Timestamp,
    samples_per_frame: i64,
    video_end: Timestamp,
    policy: AudioBoundaryPolicy,
) -> Result<usize> {
    let mut selected = 0_usize;
    for index in 0..available {
        let index = i64::try_from(index)
            .map_err(|_| Error::InvalidData("audio frame index does not fit i64".into()))?;
        let frame_start =
            Timestamp {
                value: start
                    .value
                    .checked_add(index.checked_mul(samples_per_frame).ok_or_else(|| {
                        Error::InvalidData("audio frame timestamp overflows".into())
                    })?)
                    .ok_or_else(|| Error::InvalidData("audio frame timestamp overflows".into()))?,
                time_base: start.time_base,
            };
        let frame_end = Timestamp {
            value: frame_start
                .value
                .checked_add(samples_per_frame)
                .ok_or_else(|| Error::InvalidData("audio frame end overflows".into()))?,
            time_base: start.time_base,
        };
        let keep = match policy {
            AudioBoundaryPolicy::Exact | AudioBoundaryPolicy::Cover => {
                compare_timestamps(frame_start, video_end)? == Ordering::Less
            }
            AudioBoundaryPolicy::Contained => {
                compare_timestamps(frame_end, video_end)? != Ordering::Greater
            }
        };
        if !keep {
            break;
        }
        selected += 1;
    }
    let selected = i64::try_from(selected)
        .map_err(|_| Error::InvalidData("selected audio frame count does not fit i64".into()))?;
    let selected_end =
        Timestamp {
            value: start
                .value
                .checked_add(selected.checked_mul(samples_per_frame).ok_or_else(|| {
                    Error::InvalidData("selected audio duration overflows".into())
                })?)
                .ok_or_else(|| Error::InvalidData("selected audio end overflows".into()))?,
            time_base: start.time_base,
        };
    let end_order = compare_timestamps(selected_end, video_end)?;
    match policy {
        AudioBoundaryPolicy::Exact if end_order != Ordering::Equal => Err(Error::InvalidData(
            "complete Layer II frames cannot end exactly with the video".into(),
        )),
        AudioBoundaryPolicy::Cover if end_order == Ordering::Less => Err(Error::InvalidData(
            "Layer II input does not contain enough complete frames to cover the video end".into(),
        )),
        _ => usize::try_from(selected).map_err(|_| {
            Error::InvalidData("selected audio frame count does not fit usize".into())
        }),
    }
}

fn compare_timestamps(left: Timestamp, right: Timestamp) -> Result<Ordering> {
    validate_time_base(left)?;
    validate_time_base(right)?;
    let left_value = i128::from(left.value)
        .checked_mul(i128::from(left.time_base.numerator()))
        .and_then(|value| value.checked_mul(i128::from(right.time_base.denominator())))
        .ok_or_else(|| Error::InvalidData("timestamp comparison overflows".into()))?;
    let right_value = i128::from(right.value)
        .checked_mul(i128::from(right.time_base.numerator()))
        .and_then(|value| value.checked_mul(i128::from(left.time_base.denominator())))
        .ok_or_else(|| Error::InvalidData("timestamp comparison overflows".into()))?;
    Ok(left_value.cmp(&right_value))
}

fn transport_clock(timestamp: Timestamp) -> Result<i64> {
    Ok(timestamp
        .rescale(
            Rational::new(1, SYSTEM_CLOCK_FREQUENCY)?,
            TimestampRounding::TowardZero,
        )?
        .value)
}

fn timestamp_delta_micros(left: Timestamp, right: Timestamp) -> Result<i64> {
    validate_time_base(left)?;
    validate_time_base(right)?;
    let denominator = i128::from(left.time_base.denominator())
        .checked_mul(i128::from(right.time_base.denominator()))
        .ok_or_else(|| Error::InvalidData("timestamp delta denominator overflows".into()))?;
    let left_value = i128::from(left.value)
        .checked_mul(i128::from(left.time_base.numerator()))
        .and_then(|value| value.checked_mul(i128::from(right.time_base.denominator())))
        .ok_or_else(|| Error::InvalidData("timestamp delta overflows".into()))?;
    let right_value = i128::from(right.value)
        .checked_mul(i128::from(right.time_base.numerator()))
        .and_then(|value| value.checked_mul(i128::from(left.time_base.denominator())))
        .ok_or_else(|| Error::InvalidData("timestamp delta overflows".into()))?;
    let scaled = left_value
        .checked_sub(right_value)
        .and_then(|value| value.checked_mul(1_000_000))
        .ok_or_else(|| Error::InvalidData("timestamp delta overflows".into()))?;
    let quotient = scaled / denominator;
    let remainder = scaled % denominator;
    let rounded = if remainder
        .abs()
        .checked_mul(2)
        .is_some_and(|twice| twice >= denominator)
    {
        quotient + if remainder.is_negative() { -1 } else { 1 }
    } else {
        quotient
    };
    i64::try_from(rounded)
        .map_err(|_| Error::InvalidData("timestamp delta does not fit i64".into()))
}

fn validate_time_base(timestamp: Timestamp) -> Result<()> {
    if timestamp.time_base.numerator() <= 0 || timestamp.time_base.denominator() <= 0 {
        return Err(Error::InvalidData(
            "timestamp time bases must be positive".into(),
        ));
    }
    Ok(())
}
