[package]
name = "mmrecode-mmfx"
description = "Typed scene language, render graph, and reference backend for MMRecode"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
parley.workspace = true
swash.workspace = true
zeno.workspace = true

[lints]
workspace = true
