[package]
name = "mmrecode-mpegaudio"
description = "MPEG audio elementary-stream framing for MMRecode"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mmrecode-core.workspace = true

[lints]
workspace = true
