[package]
name = "mmrecode-viewer"
description = "Visual codec and frame inspection tool for MMRecode"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
eframe.workspace = true
mmrecode-core.workspace = true
mmrecode-dv.workspace = true
mmrecode-mjpeg.workspace = true
mmrecode-mpegaudio.workspace = true
mmrecode-mpeg2.workspace = true
mmrecode-mpegts.workspace = true
mmrecode-playback.workspace = true
mmrecode-y4m.workspace = true
rodio.workspace = true

[lints]
workspace = true
