[package]
name = "mmrecode-mpeg2"
description = "Native MPEG-2 Video elementary-stream codec for MMRecode"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mmrecode-bitstream.workspace = true
mmrecode-core.workspace = true

[dev-dependencies]
mmrecode-quality.workspace = true
mmrecode-testkit.workspace = true
mmrecode-y4m.workspace = true

[lints]
workspace = true
