//! Recursive linked-media authoring model.

use std::{collections::BTreeMap, path::PathBuf};

use mmrecode_core::{Error, Rational, Result, Timestamp, TimestampRounding};

use crate::TimeRange;

/// Stable identity of one reusable media definition.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MediaId(pub u64);

/// Stable identity of one placement link in a parent's local timeline.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MediaLinkId(pub u64);

/// Extensible namespaced kind of a media node, such as `video`, `text`, or `fx/blur`.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MediaKind(String);

impl MediaKind {
    /// Creates a non-empty media kind.
    ///
    /// # Errors
    ///
    /// Returns an error when `value` is empty after trimming.
    pub fn new(value: impl Into<String>) -> Result<Self> {
        let value = value.into();
        if value.trim().is_empty() {
            return Err(Error::InvalidData("media kind cannot be empty".into()));
        }
        Ok(Self(value))
    }

    /// Returns the stable textual media kind.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// How visual media is mapped into its parent canvas.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
#[non_exhaustive]
pub enum VisualScaleMode {
    /// Preserve aspect ratio and show the complete image, adding background bars when necessary.
    #[default]
    Fit,
    /// Preserve aspect ratio and fill the canvas, cropping centered excess pixels.
    Fill,
    /// Ignore aspect ratio and resize directly to the complete canvas.
    Stretch,
    /// Keep native pixel size, centered, cropping or padding at the canvas edges.
    Native,
}

impl VisualScaleMode {
    /// Returns the stable editor/project-file spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Fit => "fit",
            Self::Fill => "fill",
            Self::Stretch => "stretch",
            Self::Native => "native",
        }
    }
}

/// Where the content represented by a media node originates.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum MediaOrigin {
    /// Content generated by the project, including text, shapes, and effects.
    Generated,
    /// Media stored at a path relative to the project file.
    Managed {
        /// Path resolved relative to the project file.
        path: PathBuf,
    },
    /// Media intentionally linked outside the portable project directory.
    External {
        /// Explicit external path retained outside the project bundle.
        path: PathBuf,
    },
}

/// Source payload owned by one generated MMFX media definition.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MmfxSource {
    /// Authoritative MMFX scene source stored inside the project document.
    pub source: String,
    /// Optional directory used to resolve module-relative resources imported from an external file.
    pub resource_base: Option<PathBuf>,
}

/// Reusable media definition that may establish its own local child timeline.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaNode {
    /// Stable media identity.
    pub id: MediaId,
    /// Human-facing definition name; placement paths use link aliases instead.
    pub name: String,
    /// Extensible media kind.
    pub kind: MediaKind,
    /// Native local time base of this media definition.
    pub time_base: Rational,
    /// Current local presentation duration.
    pub duration: Timestamp,
    /// Content origin.
    pub origin: MediaOrigin,
    /// Embedded MMFX source for `fx` media; absent for every other media kind.
    pub mmfx: Option<MmfxSource>,
    children: Vec<MediaLinkId>,
}

impl MediaNode {
    /// Returns placement links in deterministic composition order.
    #[must_use]
    pub fn children(&self) -> &[MediaLinkId] {
        &self.children
    }
}

/// Placement of one media definition in another media node's local timeline.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaLink {
    /// Stable placement identity.
    pub id: MediaLinkId,
    /// Parent media whose local timeline contains this placement.
    pub parent_id: MediaId,
    /// Reusable media definition being placed.
    pub media_id: MediaId,
    /// Human-facing path component, unique among siblings.
    pub alias: String,
    /// Selected interval in the child media's native time base.
    pub source_range: TimeRange,
    /// Placement interval in the parent's local time base.
    pub timeline_range: TimeRange,
    /// Visual mapping into the parent canvas; ignored by non-visual media.
    pub scale_mode: VisualScaleMode,
}

/// Contextual path through placement links from the project root.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct MediaPath {
    links: Vec<MediaLinkId>,
}

impl MediaPath {
    /// Returns the root path.
    #[must_use]
    pub fn root() -> Self {
        Self::default()
    }

    /// Returns the traversed link identities.
    #[must_use]
    pub fn links(&self) -> &[MediaLinkId] {
        &self.links
    }

    /// Returns the current placement link, or `None` at the project root.
    #[must_use]
    pub fn current_link(&self) -> Option<MediaLinkId> {
        self.links.last().copied()
    }

    pub(crate) fn push(&mut self, link_id: MediaLinkId) {
        self.links.push(link_id);
    }

    pub(crate) fn pop(&mut self) {
        self.links.pop();
    }

    pub(crate) fn clear(&mut self) {
        self.links.clear();
    }
}

/// One row returned when inspecting the current media's local timeline.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaListing {
    /// Stable placement identity.
    pub link_id: MediaLinkId,
    /// Placement alias used by navigation.
    pub alias: String,
    /// Kind of the linked media definition.
    pub kind: MediaKind,
    /// Parent-local placement interval.
    pub timeline_range: TimeRange,
}

/// Scan organization of the project canvas.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum ProjectScanMode {
    /// Every project frame contains a complete progressive image.
    Progressive,
    /// Every project frame is presented as two interlaced fields.
    Interlaced,
}

/// Working color description used by generated and composited project pixels.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum ProjectColorSpace {
    /// ITU-R BT.709 working color for conventional HD video.
    Rec709,
    /// sRGB working color for graphics-oriented projects.
    Srgb,
    /// ITU-R BT.2020 working color for wide-gamut UHD projects.
    Rec2020,
}

/// How root-timeline positions behave when the project frame rate changes.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum ProjectRateConformPolicy {
    /// Preserve presentation time and round root placement boundaries to the nearest new frame.
    PreserveTime,
    /// Preserve integer frame numbers, intentionally changing their presentation time.
    PreserveFrames,
}

/// Accounting returned after a project frame-rate change.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ProjectRateConformReport {
    /// Number of direct root placements whose timeline time base changed.
    pub conformed_placements: usize,
    /// Number of start/end boundaries that required nearest-frame rounding.
    pub rounded_boundaries: usize,
}

/// Authoring properties of the project root, independent of delivery codecs and containers.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectSettings {
    /// Root canvas width in pixels.
    pub width: u32,
    /// Root canvas height in pixels.
    pub height: u32,
    /// Exact project frame rate in frames per second.
    pub frame_rate: Rational,
    /// Horizontal-to-vertical pixel aspect ratio.
    pub pixel_aspect: Rational,
    /// Progressive or interlaced project organization.
    pub scan_mode: ProjectScanMode,
    /// Working color description for compositing and generated content.
    pub color_space: ProjectColorSpace,
    /// Project audio sample rate in hertz.
    pub audio_sample_rate: u32,
    /// Project output channel count.
    pub audio_channels: u16,
    /// Preset from which these resolved values originated, when known.
    pub base_preset: Option<String>,
}

impl ProjectSettings {
    /// Returns resolved settings for a built-in authoring preset.
    ///
    /// Presets establish authoring geometry and timing only. Delivery codecs remain export
    /// settings and may differ between several exports of the same project.
    ///
    /// # Errors
    ///
    /// Returns an error when `name` is not a known built-in preset.
    pub fn from_preset(name: &str) -> Result<Self> {
        let (width, height, rate_numerator, rate_denominator, scan_mode) = match name {
            "web-1080p30" | "youtube-1080p30" => {
                (1_920, 1_080, 30, 1, ProjectScanMode::Progressive)
            }
            "youtube-2160p30" => (3_840, 2_160, 30, 1, ProjectScanMode::Progressive),
            "pal-576i25" => (720, 576, 25, 1, ProjectScanMode::Interlaced),
            _ => {
                return Err(Error::InvalidData(format!(
                    "unknown project preset '{name}'; available: {}",
                    Self::preset_names().join(", ")
                )));
            }
        };
        Ok(Self {
            width,
            height,
            frame_rate: Rational::new(rate_numerator, rate_denominator)?,
            pixel_aspect: Rational::new(1, 1)?,
            scan_mode,
            color_space: ProjectColorSpace::Rec709,
            audio_sample_rate: 48_000,
            audio_channels: 2,
            base_preset: Some(name.into()),
        })
    }

    /// Returns the stable names of all built-in authoring presets.
    #[must_use]
    pub const fn preset_names() -> &'static [&'static str] {
        &[
            "web-1080p30",
            "youtube-1080p30",
            "youtube-2160p30",
            "pal-576i25",
        ]
    }

    /// Returns the exact duration of one project frame.
    ///
    /// # Errors
    ///
    /// Returns an error if the stored frame rate is invalid.
    pub fn time_base(&self) -> Result<Rational> {
        Rational::new(self.frame_rate.denominator(), self.frame_rate.numerator())
    }

    /// Validates project dimensions, timing, pixel geometry, and audio defaults.
    ///
    /// # Errors
    ///
    /// Returns an error for a zero or unreasonable dimension, non-positive rational, unsupported
    /// channel count, or audio rate outside the authoring range.
    pub fn validate(&self) -> Result<()> {
        if self.width == 0 || self.height == 0 || self.width > 32_768 || self.height > 32_768 {
            return Err(Error::InvalidData(
                "project dimensions must be from 1 through 32768 pixels".into(),
            ));
        }
        if self.frame_rate.numerator() <= 0 || self.pixel_aspect.numerator() <= 0 {
            return Err(Error::InvalidData(
                "project frame rate and pixel aspect must be positive".into(),
            ));
        }
        if !(8_000..=384_000).contains(&self.audio_sample_rate) {
            return Err(Error::InvalidData(
                "project audio rate must be from 8000 through 384000 Hz".into(),
            ));
        }
        if !(1..=64).contains(&self.audio_channels) {
            return Err(Error::InvalidData(
                "project audio channels must be from 1 through 64".into(),
            ));
        }
        Ok(())
    }
}

impl Default for ProjectSettings {
    fn default() -> Self {
        Self::from_preset("web-1080p30").expect("built-in project preset must remain valid")
    }
}

/// Recursive authoring project whose root and media nodes own local linked timelines.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaProject {
    /// Human-facing project name.
    pub name: String,
    settings: ProjectSettings,
    root_id: MediaId,
    media: BTreeMap<MediaId, MediaNode>,
    links: BTreeMap<MediaLinkId, MediaLink>,
    next_media_id: u64,
    next_link_id: u64,
}

impl MediaProject {
    /// Creates an empty project root in `time_base`.
    ///
    /// # Errors
    ///
    /// Returns an error for an empty project name or non-positive time base.
    pub fn new(name: impl Into<String>, time_base: Rational) -> Result<Self> {
        let settings = ProjectSettings {
            frame_rate: Rational::new(time_base.denominator(), time_base.numerator())?,
            base_preset: None,
            ..ProjectSettings::default()
        };
        Self::with_settings(name, settings)
    }

    /// Creates an empty project root with fully resolved authoring settings.
    ///
    /// # Errors
    ///
    /// Returns an error for an empty name or invalid project settings.
    pub fn with_settings(name: impl Into<String>, settings: ProjectSettings) -> Result<Self> {
        let name = name.into();
        if name.trim().is_empty() {
            return Err(Error::InvalidData("project name cannot be empty".into()));
        }
        settings.validate()?;
        let time_base = settings.time_base()?;
        let root_id = MediaId(1);
        let root = MediaNode {
            id: root_id,
            name: name.clone(),
            kind: MediaKind::new("project")?,
            time_base,
            duration: Timestamp {
                value: 0,
                time_base,
            },
            origin: MediaOrigin::Generated,
            mmfx: None,
            children: Vec::new(),
        };
        Ok(Self {
            name,
            settings,
            root_id,
            media: BTreeMap::from([(root_id, root)]),
            links: BTreeMap::new(),
            next_media_id: 2,
            next_link_id: 1,
        })
    }

    /// Creates an empty project from a built-in authoring preset.
    ///
    /// # Errors
    ///
    /// Returns an error for an unknown preset or invalid project name.
    pub fn from_preset(name: impl Into<String>, preset: &str) -> Result<Self> {
        Self::with_settings(name, ProjectSettings::from_preset(preset)?)
    }

    /// Renames the project and its generated root media node.
    ///
    /// # Errors
    ///
    /// Returns an error when `name` is empty after trimming or the project root is missing.
    pub fn set_name(&mut self, name: impl Into<String>) -> Result<()> {
        let name = name.into();
        if name.trim().is_empty() {
            return Err(Error::InvalidData("project name cannot be empty".into()));
        }
        self.media
            .get_mut(&self.root_id)
            .ok_or_else(|| Error::InvalidState("project root disappeared".into()))?
            .name
            .clone_from(&name);
        self.name = name;
        Ok(())
    }

    /// Returns resolved authoring settings for the project root.
    #[must_use]
    pub const fn settings(&self) -> &ProjectSettings {
        &self.settings
    }

    /// Replaces resolved authoring settings, preserving root-timeline presentation time when the
    /// frame rate changes.
    ///
    /// # Errors
    ///
    /// Returns an error for invalid settings, arithmetic overflow, or a placement that would
    /// collapse below one frame after conformance.
    pub fn set_settings(&mut self, settings: ProjectSettings) -> Result<()> {
        self.set_settings_with_rate_conform(settings, ProjectRateConformPolicy::PreserveTime)
            .map(|_| ())
    }

    /// Replaces settings with an explicit root-timeline frame-rate conformance policy.
    ///
    /// Source ranges and nested media time bases remain untouched. Only direct placements in the
    /// project root use the project time base and therefore require conformance.
    ///
    /// # Errors
    ///
    /// Returns an error for invalid settings, arithmetic overflow, or a placement that would
    /// collapse below one frame after time-preserving conformance.
    pub fn set_settings_with_rate_conform(
        &mut self,
        settings: ProjectSettings,
        policy: ProjectRateConformPolicy,
    ) -> Result<ProjectRateConformReport> {
        settings.validate()?;
        let old_time_base = self.settings.time_base()?;
        let new_time_base = settings.time_base()?;
        let mut report = ProjectRateConformReport::default();
        if old_time_base != new_time_base {
            let child_ids = self
                .media
                .get(&self.root_id)
                .ok_or_else(|| Error::InvalidState("project root disappeared".into()))?
                .children
                .clone();
            let conformed = child_ids
                .iter()
                .map(|link_id| {
                    let link = self.links.get(link_id).ok_or_else(|| {
                        Error::InvalidState("project root child link disappeared".into())
                    })?;
                    let (start, end, rounded) = match policy {
                        ProjectRateConformPolicy::PreserveTime => {
                            let start = link.timeline_range.start;
                            let end = link.timeline_range.end;
                            let rounded = usize::from(
                                start.rescale(new_time_base, TimestampRounding::Exact).is_err(),
                            ) + usize::from(
                                end.rescale(new_time_base, TimestampRounding::Exact).is_err(),
                            );
                            (
                                start.rescale(new_time_base, TimestampRounding::NearestTiesAway)?,
                                end.rescale(new_time_base, TimestampRounding::NearestTiesAway)?,
                                rounded,
                            )
                        }
                        ProjectRateConformPolicy::PreserveFrames => (
                            Timestamp {
                                value: link.timeline_range.start.value,
                                time_base: new_time_base,
                            },
                            Timestamp {
                                value: link.timeline_range.end.value,
                                time_base: new_time_base,
                            },
                            0,
                        ),
                    };
                    if start.value >= end.value {
                        return Err(Error::Unsupported(format!(
                            "project rate conformance would collapse placement '{}' below one frame",
                            link.alias
                        )));
                    }
                    Ok((*link_id, TimeRange::new(start, end)?, rounded))
                })
                .collect::<Result<Vec<_>>>()?;
            for (link_id, timeline_range, rounded) in conformed {
                let link = self.links.get_mut(&link_id).ok_or_else(|| {
                    Error::InvalidState("project root child link disappeared".into())
                })?;
                link.timeline_range = timeline_range;
                report.conformed_placements += 1;
                report.rounded_boundaries += rounded;
            }
            let root_duration = child_ids
                .iter()
                .filter_map(|link_id| self.links.get(link_id))
                .map(|link| link.timeline_range.end.value)
                .max()
                .unwrap_or(0);
            let root = self
                .media
                .get_mut(&self.root_id)
                .ok_or_else(|| Error::InvalidState("project root disappeared".into()))?;
            root.time_base = new_time_base;
            root.duration.time_base = new_time_base;
            root.duration.value = root_duration;
        }
        self.settings = settings;
        Ok(report)
    }

    /// Returns media definitions in stable identifier order.
    pub fn media_nodes(&self) -> impl Iterator<Item = &MediaNode> {
        self.media.values()
    }

    /// Returns placement links in stable identifier order.
    pub fn placement_links(&self) -> impl Iterator<Item = &MediaLink> {
        self.links.values()
    }

    /// Returns the stable project-root media identity.
    #[must_use]
    pub fn root_id(&self) -> MediaId {
        self.root_id
    }

    /// Returns one media definition.
    #[must_use]
    pub fn media(&self, id: MediaId) -> Option<&MediaNode> {
        self.media.get(&id)
    }

    /// Returns one placement link.
    #[must_use]
    pub fn link(&self, id: MediaLinkId) -> Option<&MediaLink> {
        self.links.get(&id)
    }

    /// Resolves the current media definition reached by a contextual path.
    ///
    /// # Errors
    ///
    /// Returns an error when a link is missing or does not continue from the previous media.
    pub fn resolve_path(&self, path: &MediaPath) -> Result<MediaId> {
        let mut current = self.root_id;
        for link_id in path.links() {
            let link = self.links.get(link_id).ok_or_else(|| {
                Error::InvalidData(format!("media path references missing link {link_id:?}"))
            })?;
            if link.parent_id != current {
                return Err(Error::InvalidData(
                    "media path contains a disconnected placement link".into(),
                ));
            }
            current = link.media_id;
        }
        Ok(current)
    }

    /// Creates an unattached reusable media definition.
    ///
    /// # Errors
    ///
    /// Returns an error when its name is empty, time base is invalid, duration is negative, or an
    /// identifier overflows.
    pub fn create_media(
        &mut self,
        name: impl Into<String>,
        kind: MediaKind,
        time_base: Rational,
        duration: i64,
        origin: MediaOrigin,
    ) -> Result<MediaId> {
        let name = name.into();
        if name.trim().is_empty() {
            return Err(Error::InvalidData("media name cannot be empty".into()));
        }
        if time_base.numerator() <= 0 || duration < 0 {
            return Err(Error::InvalidData(
                "media time base must be positive and duration cannot be negative".into(),
            ));
        }
        let id = MediaId(self.next_media_id);
        self.next_media_id = self
            .next_media_id
            .checked_add(1)
            .ok_or_else(|| Error::InvalidData("media identifier overflows".into()))?;
        self.media.insert(
            id,
            MediaNode {
                id,
                name,
                kind,
                time_base,
                duration: Timestamp {
                    value: duration,
                    time_base,
                },
                origin,
                mmfx: None,
                children: Vec::new(),
            },
        );
        Ok(id)
    }

    /// Replaces the embedded source owned by one generated `fx` media definition.
    ///
    /// # Errors
    ///
    /// Returns an error when the media is missing, is not `fx`, or has a non-generated origin.
    pub fn set_mmfx_source(&mut self, media_id: MediaId, source: MmfxSource) -> Result<()> {
        let media = self
            .media
            .get_mut(&media_id)
            .ok_or_else(|| Error::InvalidData(format!("missing media {media_id:?}")))?;
        if media.kind.as_str() != "fx" || media.origin != MediaOrigin::Generated {
            return Err(Error::Unsupported(
                "MMFX source can only be attached to generated 'fx' media".into(),
            ));
        }
        media.mmfx = Some(source);
        Ok(())
    }

    /// Places media in a parent's local timeline.
    ///
    /// # Errors
    ///
    /// Returns an error for missing nodes, duplicate/invalid aliases, inconsistent time bases,
    /// unequal source/timeline durations after nearest-frame conformance, invalid ranges, or a
    /// composition cycle.
    pub fn link_media(
        &mut self,
        parent_id: MediaId,
        media_id: MediaId,
        alias: impl Into<String>,
        source_range: TimeRange,
        timeline_range: TimeRange,
    ) -> Result<MediaLinkId> {
        let alias = alias.into();
        validate_alias(&alias)?;
        let parent = self
            .media
            .get(&parent_id)
            .ok_or_else(|| Error::InvalidData(format!("missing parent media {parent_id:?}")))?;
        let child = self
            .media
            .get(&media_id)
            .ok_or_else(|| Error::InvalidData(format!("missing child media {media_id:?}")))?;
        if timeline_range.start.time_base != parent.time_base
            || source_range.start.time_base != child.time_base
        {
            return Err(Error::InvalidData(
                "media link ranges use the wrong parent or child time base".into(),
            ));
        }
        TimeRange::new(source_range.start, source_range.end)?;
        TimeRange::new(timeline_range.start, timeline_range.end)?;
        if source_range.start.value < 0 || source_range.end.value > child.duration.value {
            return Err(Error::InvalidData(
                "media link source range lies outside the child duration".into(),
            ));
        }
        let source_duration = source_range
            .duration()?
            .rescale(parent.time_base, TimestampRounding::NearestTiesAway)?;
        if source_duration.value != timeline_range.duration()?.value {
            return Err(Error::Unsupported(
                "initial media links cannot change playback speed".into(),
            ));
        }
        if parent.children.iter().any(|link_id| {
            self.links
                .get(link_id)
                .is_some_and(|link| link.alias == alias)
        }) {
            return Err(Error::InvalidData(format!(
                "media alias '{alias}' already exists in this local timeline"
            )));
        }
        if parent_id == media_id || self.reaches(media_id, parent_id) {
            return Err(Error::InvalidData(
                "media placement would create a composition cycle".into(),
            ));
        }
        let id = MediaLinkId(self.next_link_id);
        self.next_link_id = self
            .next_link_id
            .checked_add(1)
            .ok_or_else(|| Error::InvalidData("media-link identifier overflows".into()))?;
        self.links.insert(
            id,
            MediaLink {
                id,
                parent_id,
                media_id,
                alias,
                source_range,
                timeline_range,
                scale_mode: VisualScaleMode::default(),
            },
        );
        let parent = self
            .media
            .get_mut(&parent_id)
            .ok_or_else(|| Error::InvalidState("validated parent media disappeared".into()))?;
        parent.children.push(id);
        if timeline_range.end.value > parent.duration.value {
            parent.duration.value = timeline_range.end.value;
        }
        Ok(id)
    }

    /// Changes the visual scaling policy of one placement.
    ///
    /// # Errors
    ///
    /// Returns an error when `link_id` does not identify a placement.
    pub fn set_link_scale_mode(
        &mut self,
        link_id: MediaLinkId,
        mode: VisualScaleMode,
    ) -> Result<()> {
        self.links
            .get_mut(&link_id)
            .ok_or_else(|| Error::InvalidData(format!("missing media link {link_id:?}")))?
            .scale_mode = mode;
        Ok(())
    }

    /// Changes the visual scaling policy of the placement selected by `path`.
    ///
    /// # Errors
    ///
    /// Returns an error at the project root or for an invalid placement path.
    pub fn set_scale_mode(&mut self, path: &MediaPath, mode: VisualScaleMode) -> Result<()> {
        let link_id = path.current_link().ok_or_else(|| {
            Error::Unsupported("the project root has no placement scale mode".into())
        })?;
        self.set_link_scale_mode(link_id, mode)
    }

    /// Creates generated media and immediately links it into `parent_id`.
    ///
    /// # Errors
    ///
    /// Returns the same validation errors as [`Self::create_media`] and [`Self::link_media`].
    pub fn add_generated(
        &mut self,
        parent_id: MediaId,
        kind: MediaKind,
        alias: impl Into<String>,
        start: i64,
        duration: i64,
    ) -> Result<MediaLinkId> {
        if start < 0 || duration <= 0 {
            return Err(Error::InvalidData(
                "generated media start cannot be negative and duration must be positive".into(),
            ));
        }
        let alias = alias.into();
        let time_base = self
            .media(parent_id)
            .ok_or_else(|| Error::InvalidData(format!("missing parent media {parent_id:?}")))?
            .time_base;
        let media_id = self.create_media(
            alias.clone(),
            kind,
            time_base,
            duration,
            MediaOrigin::Generated,
        )?;
        let end = start
            .checked_add(duration)
            .ok_or_else(|| Error::InvalidData("generated media placement overflows".into()))?;
        self.link_media(
            parent_id,
            media_id,
            alias,
            time_range(0, duration, time_base)?,
            time_range(start, end, time_base)?,
        )
    }

    /// Returns child placements of the media reached by `path`.
    ///
    /// # Errors
    ///
    /// Returns an error for an invalid path or corrupted link reference.
    pub fn list(&self, path: &MediaPath) -> Result<Vec<MediaListing>> {
        let media_id = self.resolve_path(path)?;
        let media = self
            .media(media_id)
            .ok_or_else(|| Error::InvalidState("resolved media disappeared".into()))?;
        media
            .children()
            .iter()
            .map(|link_id| {
                let link = self
                    .links
                    .get(link_id)
                    .ok_or_else(|| Error::InvalidState("media child link disappeared".into()))?;
                let child = self
                    .media
                    .get(&link.media_id)
                    .ok_or_else(|| Error::InvalidState("linked child media disappeared".into()))?;
                Ok(MediaListing {
                    link_id: *link_id,
                    alias: link.alias.clone(),
                    kind: child.kind.clone(),
                    timeline_range: link.timeline_range,
                })
            })
            .collect()
    }

    /// Finds a child placement by alias or zero-based composition index.
    ///
    /// # Errors
    ///
    /// Returns an error for an invalid path or missing child selector.
    pub fn child(&self, path: &MediaPath, selector: &str) -> Result<MediaLinkId> {
        let media_id = self.resolve_path(path)?;
        let media = self
            .media(media_id)
            .ok_or_else(|| Error::InvalidState("resolved media disappeared".into()))?;
        if let Ok(index) = selector.parse::<usize>() {
            return media.children.get(index).copied().ok_or_else(|| {
                Error::InvalidData(format!("local media index {index} does not exist"))
            });
        }
        media
            .children
            .iter()
            .find_map(|link_id| {
                self.links
                    .get(link_id)
                    .filter(|link| link.alias == selector)
                    .map(|_| *link_id)
            })
            .ok_or_else(|| {
                Error::InvalidData(format!("local media alias '{selector}' does not exist"))
            })
    }

    /// Returns a slash-separated placement path.
    ///
    /// # Errors
    ///
    /// Returns an error when the path is invalid.
    pub fn display_path(&self, path: &MediaPath) -> Result<String> {
        self.resolve_path(path)?;
        if path.links().is_empty() {
            return Ok("/".into());
        }
        let aliases = path
            .links()
            .iter()
            .map(|link_id| {
                self.links
                    .get(link_id)
                    .map(|link| link.alias.as_str())
                    .ok_or_else(|| Error::InvalidState("media path link disappeared".into()))
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(format!("/{}", aliases.join("/")))
    }

    /// Trims the current placement's source and parent-local beginning.
    ///
    /// `value` is absolute in child frames unless `relative` is true.
    ///
    /// # Errors
    ///
    /// Returns an error for the root, invalid ranges, or negative time.
    pub fn trim_in(&mut self, path: &MediaPath, value: i64, relative: bool) -> Result<()> {
        let link_id = path.current_link().ok_or_else(|| {
            Error::Unsupported("the project root has no placement in-point".into())
        })?;
        let link = self
            .links
            .get(&link_id)
            .cloned()
            .ok_or_else(|| Error::InvalidData("current media link is missing".into()))?;
        let source_start = if relative {
            link.source_range
                .start
                .value
                .checked_add(value)
                .ok_or_else(|| Error::InvalidData("media in-point overflows".into()))?
        } else {
            value
        };
        if source_start < 0 || source_start >= link.source_range.end.value {
            return Err(Error::InvalidData(
                "media in-point must precede its out-point and cannot be negative".into(),
            ));
        }
        let delta = timestamp(
            source_start - link.source_range.start.value,
            link.source_range.start.time_base,
        )
        .rescale(
            link.timeline_range.start.time_base,
            TimestampRounding::NearestTiesAway,
        )?;
        let timeline_start = link
            .timeline_range
            .start
            .value
            .checked_add(delta.value)
            .ok_or_else(|| Error::InvalidData("media timeline in-point overflows".into()))?;
        if timeline_start < 0 || timeline_start >= link.timeline_range.end.value {
            return Err(Error::InvalidData(
                "trimmed media placement has an invalid timeline range".into(),
            ));
        }
        let link = self
            .links
            .get_mut(&link_id)
            .ok_or_else(|| Error::InvalidState("current media link disappeared".into()))?;
        link.source_range.start.value = source_start;
        link.timeline_range.start.value = timeline_start;
        Ok(())
    }

    /// Trims the current placement's source and parent-local ending.
    ///
    /// `value` is absolute in child frames unless `relative` is true.
    ///
    /// # Errors
    ///
    /// Returns an error for the root or invalid ranges.
    pub fn trim_out(&mut self, path: &MediaPath, value: i64, relative: bool) -> Result<()> {
        let link_id = path.current_link().ok_or_else(|| {
            Error::Unsupported("the project root has no placement out-point".into())
        })?;
        let link = self
            .links
            .get(&link_id)
            .cloned()
            .ok_or_else(|| Error::InvalidData("current media link is missing".into()))?;
        let source_end = if relative {
            link.source_range
                .end
                .value
                .checked_add(value)
                .ok_or_else(|| Error::InvalidData("media out-point overflows".into()))?
        } else {
            value
        };
        let child_duration = self
            .media(link.media_id)
            .ok_or_else(|| Error::InvalidState("linked media disappeared".into()))?
            .duration
            .value;
        if source_end <= link.source_range.start.value || source_end > child_duration {
            return Err(Error::InvalidData(
                "media out-point must follow its in-point and stay inside the source".into(),
            ));
        }
        let delta = timestamp(
            source_end - link.source_range.end.value,
            link.source_range.end.time_base,
        )
        .rescale(
            link.timeline_range.end.time_base,
            TimestampRounding::NearestTiesAway,
        )?;
        let timeline_end = link
            .timeline_range
            .end
            .value
            .checked_add(delta.value)
            .ok_or_else(|| Error::InvalidData("media timeline out-point overflows".into()))?;
        if timeline_end <= link.timeline_range.start.value {
            return Err(Error::InvalidData(
                "trimmed media placement has an invalid timeline range".into(),
            ));
        }
        let link = self
            .links
            .get_mut(&link_id)
            .ok_or_else(|| Error::InvalidState("current media link disappeared".into()))?;
        link.source_range.end.value = source_end;
        link.timeline_range.end.value = timeline_end;
        let parent_id = link.parent_id;
        if parent_id == self.root_id {
            let duration = self
                .media
                .get(&parent_id)
                .ok_or_else(|| Error::InvalidState("project root disappeared".into()))?
                .children
                .iter()
                .filter_map(|child_id| self.links.get(child_id))
                .map(|child| child.timeline_range.end.value)
                .max()
                .unwrap_or(0);
            self.media
                .get_mut(&parent_id)
                .ok_or_else(|| Error::InvalidState("project root disappeared".into()))?
                .duration
                .value = duration;
        }
        Ok(())
    }

    fn reaches(&self, start: MediaId, target: MediaId) -> bool {
        let mut pending = vec![start];
        let mut visited = std::collections::BTreeSet::new();
        while let Some(media_id) = pending.pop() {
            if media_id == target {
                return true;
            }
            if !visited.insert(media_id) {
                continue;
            }
            if let Some(media) = self.media.get(&media_id) {
                pending.extend(
                    media
                        .children
                        .iter()
                        .filter_map(|link_id| self.links.get(link_id).map(|link| link.media_id)),
                );
            }
        }
        false
    }
}

fn validate_alias(alias: &str) -> Result<()> {
    if alias.trim().is_empty()
        || alias.contains('/')
        || alias == "."
        || alias == ".."
        || alias.chars().any(char::is_control)
    {
        return Err(Error::InvalidData(format!(
            "'{alias}' is not a valid media-link alias"
        )));
    }
    Ok(())
}

fn timestamp(value: i64, time_base: Rational) -> Timestamp {
    Timestamp { value, time_base }
}

fn time_range(start: i64, end: i64, time_base: Rational) -> Result<TimeRange> {
    TimeRange::new(timestamp(start, time_base), timestamp(end, time_base))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> MediaProject {
        MediaProject::new("Film", Rational::new(1, 25).unwrap()).unwrap()
    }

    #[test]
    fn recursively_links_media_without_artificial_tracks() {
        let mut project = project();
        let clip = project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                0,
                100,
            )
            .unwrap();
        let mut clip_path = MediaPath::root();
        clip_path.push(clip);
        let clip_id = project.resolve_path(&clip_path).unwrap();
        let title = project
            .add_generated(clip_id, MediaKind::new("text").unwrap(), "Title", 10, 20)
            .unwrap();
        clip_path.push(title);

        assert_eq!(project.display_path(&clip_path).unwrap(), "/Clip0/Title");
        assert_eq!(project.list(&MediaPath::root()).unwrap()[0].alias, "Clip0");
    }

    #[test]
    fn renaming_a_project_keeps_its_root_name_in_sync() {
        let mut project = project();
        project.set_name("MyFilm").unwrap();
        assert_eq!(project.name, "MyFilm");
        assert_eq!(project.media(project.root_id()).unwrap().name, "MyFilm");
        assert!(project.set_name("  ").is_err());
    }

    #[test]
    fn rejects_composition_cycles() {
        let mut project = project();
        let time_base = Rational::new(1, 25).unwrap();
        let first = project
            .create_media(
                "First",
                MediaKind::new("group").unwrap(),
                time_base,
                10,
                MediaOrigin::Generated,
            )
            .unwrap();
        let second = project
            .create_media(
                "Second",
                MediaKind::new("group").unwrap(),
                time_base,
                10,
                MediaOrigin::Generated,
            )
            .unwrap();
        project
            .link_media(
                first,
                second,
                "Second",
                time_range(0, 10, time_base).unwrap(),
                time_range(0, 10, time_base).unwrap(),
            )
            .unwrap();
        assert!(
            project
                .link_media(
                    second,
                    first,
                    "First",
                    time_range(0, 10, time_base).unwrap(),
                    time_range(0, 10, time_base).unwrap(),
                )
                .is_err()
        );
    }

    #[test]
    fn trims_a_placement_without_mutating_the_reusable_media() {
        let mut project = project();
        let link_id = project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                5,
                100,
            )
            .unwrap();
        let mut path = MediaPath::root();
        path.push(link_id);
        project.trim_in(&path, 10, true).unwrap();
        project.trim_out(&path, -5, true).unwrap();

        let link = project.link(link_id).unwrap();
        assert_eq!(
            (link.source_range.start.value, link.source_range.end.value),
            (10, 95)
        );
        assert_eq!(
            (
                link.timeline_range.start.value,
                link.timeline_range.end.value
            ),
            (15, 100)
        );
        assert_eq!(project.media(link.media_id).unwrap().duration.value, 100);
    }

    #[test]
    fn rate_change_preserves_root_presentation_time_and_source_ranges() {
        let mut project = MediaProject::new("Film", Rational::new(1, 30).unwrap()).unwrap();
        let link_id = project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                30,
                30,
            )
            .unwrap();
        let media_id = project.link(link_id).unwrap().media_id;
        let nested_link_id = project
            .add_generated(media_id, MediaKind::new("text").unwrap(), "Title", 5, 10)
            .unwrap();
        let source_range = project.link(link_id).unwrap().source_range;
        let mut settings = project.settings().clone();
        settings.frame_rate = Rational::new(25, 1).unwrap();

        let report = project
            .set_settings_with_rate_conform(settings, ProjectRateConformPolicy::PreserveTime)
            .unwrap();
        let link = project.link(link_id).unwrap();
        assert_eq!(link.timeline_range.start.value, 25);
        assert_eq!(link.timeline_range.end.value, 50);
        assert_eq!(
            link.timeline_range.start.time_base,
            Rational::new(1, 25).unwrap()
        );
        assert_eq!(link.source_range, source_range);
        assert_eq!(
            project
                .link(nested_link_id)
                .unwrap()
                .timeline_range
                .start
                .time_base,
            Rational::new(1, 30).unwrap()
        );
        assert_eq!(report.conformed_placements, 1);
        assert_eq!(report.rounded_boundaries, 0);
        let root = project.media(project.root_id()).unwrap();
        assert_eq!(root.time_base, Rational::new(1, 25).unwrap());
        assert_eq!(root.duration.value, 50);
    }

    #[test]
    fn rate_change_can_preserve_root_frame_numbers() {
        let mut project = MediaProject::new("Film", Rational::new(1, 30).unwrap()).unwrap();
        let link_id = project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                10,
                10,
            )
            .unwrap();
        let mut settings = project.settings().clone();
        settings.frame_rate = Rational::new(25, 1).unwrap();

        let report = project
            .set_settings_with_rate_conform(settings, ProjectRateConformPolicy::PreserveFrames)
            .unwrap();
        let link = project.link(link_id).unwrap();
        assert_eq!(link.timeline_range.start.value, 10);
        assert_eq!(link.timeline_range.end.value, 20);
        assert_eq!(
            link.timeline_range.start.time_base,
            Rational::new(1, 25).unwrap()
        );
        assert_eq!(report.conformed_placements, 1);
        assert_eq!(report.rounded_boundaries, 0);
    }

    #[test]
    fn time_conformance_reports_rounded_boundaries() {
        let mut project = MediaProject::new("Film", Rational::new(1, 30).unwrap()).unwrap();
        project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                10,
                10,
            )
            .unwrap();
        let mut settings = project.settings().clone();
        settings.frame_rate = Rational::new(25, 1).unwrap();

        let report = project
            .set_settings_with_rate_conform(settings, ProjectRateConformPolicy::PreserveTime)
            .unwrap();
        assert_eq!(report.conformed_placements, 1);
        assert_eq!(report.rounded_boundaries, 2);
        let link = project.link(MediaLinkId(1)).unwrap();
        assert_eq!(link.timeline_range.start.value, 8);
        assert_eq!(link.timeline_range.end.value, 17);
    }

    #[test]
    fn collapsing_rate_conformance_is_atomic() {
        let mut project = MediaProject::new("Film", Rational::new(1, 30).unwrap()).unwrap();
        project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                1,
                1,
            )
            .unwrap();
        let before = project.clone();
        let mut settings = project.settings().clone();
        settings.frame_rate = Rational::new(1, 1).unwrap();

        assert!(
            project
                .set_settings_with_rate_conform(settings, ProjectRateConformPolicy::PreserveTime)
                .is_err()
        );
        assert_eq!(project, before);
    }
}
