//! Recursive linked-media authoring model.

use std::{collections::BTreeMap, path::PathBuf};

use mmrecode_core::{Error, Rational, Result, Timestamp, TimestampRounding};

use crate::TimeRange;

/// Stable identity of one reusable media definition.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MediaId(pub u64);

/// Stable identity of one placement link in a parent's local timeline.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MediaLinkId(pub u64);

/// Extensible namespaced kind of a media node, such as `video`, `text`, or `fx/blur`.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MediaKind(String);

impl MediaKind {
    /// Creates a non-empty media kind.
    ///
    /// # Errors
    ///
    /// Returns an error when `value` is empty after trimming.
    pub fn new(value: impl Into<String>) -> Result<Self> {
        let value = value.into();
        if value.trim().is_empty() {
            return Err(Error::InvalidData("media kind cannot be empty".into()));
        }
        Ok(Self(value))
    }

    /// Returns the stable textual media kind.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Where the content represented by a media node originates.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum MediaOrigin {
    /// Content generated by the project, including text, shapes, and effects.
    Generated,
    /// Media stored at a path relative to the project file.
    Managed {
        /// Path resolved relative to the project file.
        path: PathBuf,
    },
    /// Media intentionally linked outside the portable project directory.
    External {
        /// Explicit external path retained outside the project bundle.
        path: PathBuf,
    },
}

/// Reusable media definition that may establish its own local child timeline.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaNode {
    /// Stable media identity.
    pub id: MediaId,
    /// Human-facing definition name; placement paths use link aliases instead.
    pub name: String,
    /// Extensible media kind.
    pub kind: MediaKind,
    /// Native local time base of this media definition.
    pub time_base: Rational,
    /// Current local presentation duration.
    pub duration: Timestamp,
    /// Content origin.
    pub origin: MediaOrigin,
    children: Vec<MediaLinkId>,
}

impl MediaNode {
    /// Returns placement links in deterministic composition order.
    #[must_use]
    pub fn children(&self) -> &[MediaLinkId] {
        &self.children
    }
}

/// Placement of one media definition in another media node's local timeline.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaLink {
    /// Stable placement identity.
    pub id: MediaLinkId,
    /// Parent media whose local timeline contains this placement.
    pub parent_id: MediaId,
    /// Reusable media definition being placed.
    pub media_id: MediaId,
    /// Human-facing path component, unique among siblings.
    pub alias: String,
    /// Selected interval in the child media's native time base.
    pub source_range: TimeRange,
    /// Placement interval in the parent's local time base.
    pub timeline_range: TimeRange,
}

/// Contextual path through placement links from the project root.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct MediaPath {
    links: Vec<MediaLinkId>,
}

impl MediaPath {
    /// Returns the root path.
    #[must_use]
    pub fn root() -> Self {
        Self::default()
    }

    /// Returns the traversed link identities.
    #[must_use]
    pub fn links(&self) -> &[MediaLinkId] {
        &self.links
    }

    /// Returns the current placement link, or `None` at the project root.
    #[must_use]
    pub fn current_link(&self) -> Option<MediaLinkId> {
        self.links.last().copied()
    }

    pub(crate) fn push(&mut self, link_id: MediaLinkId) {
        self.links.push(link_id);
    }

    pub(crate) fn pop(&mut self) {
        self.links.pop();
    }

    pub(crate) fn clear(&mut self) {
        self.links.clear();
    }
}

/// One row returned when inspecting the current media's local timeline.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaListing {
    /// Stable placement identity.
    pub link_id: MediaLinkId,
    /// Placement alias used by navigation.
    pub alias: String,
    /// Kind of the linked media definition.
    pub kind: MediaKind,
    /// Parent-local placement interval.
    pub timeline_range: TimeRange,
}

/// Recursive authoring project whose root and media nodes own local linked timelines.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MediaProject {
    /// Human-facing project name.
    pub name: String,
    root_id: MediaId,
    media: BTreeMap<MediaId, MediaNode>,
    links: BTreeMap<MediaLinkId, MediaLink>,
    next_media_id: u64,
    next_link_id: u64,
}

impl MediaProject {
    /// Creates an empty project root in `time_base`.
    ///
    /// # Errors
    ///
    /// Returns an error for an empty project name or non-positive time base.
    pub fn new(name: impl Into<String>, time_base: Rational) -> Result<Self> {
        let name = name.into();
        if name.trim().is_empty() {
            return Err(Error::InvalidData("project name cannot be empty".into()));
        }
        if time_base.numerator() <= 0 {
            return Err(Error::InvalidData(
                "project time base must be positive".into(),
            ));
        }
        let root_id = MediaId(1);
        let root = MediaNode {
            id: root_id,
            name: name.clone(),
            kind: MediaKind::new("project")?,
            time_base,
            duration: Timestamp {
                value: 0,
                time_base,
            },
            origin: MediaOrigin::Generated,
            children: Vec::new(),
        };
        Ok(Self {
            name,
            root_id,
            media: BTreeMap::from([(root_id, root)]),
            links: BTreeMap::new(),
            next_media_id: 2,
            next_link_id: 1,
        })
    }

    /// Returns the stable project-root media identity.
    #[must_use]
    pub fn root_id(&self) -> MediaId {
        self.root_id
    }

    /// Returns one media definition.
    #[must_use]
    pub fn media(&self, id: MediaId) -> Option<&MediaNode> {
        self.media.get(&id)
    }

    /// Returns one placement link.
    #[must_use]
    pub fn link(&self, id: MediaLinkId) -> Option<&MediaLink> {
        self.links.get(&id)
    }

    /// Resolves the current media definition reached by a contextual path.
    ///
    /// # Errors
    ///
    /// Returns an error when a link is missing or does not continue from the previous media.
    pub fn resolve_path(&self, path: &MediaPath) -> Result<MediaId> {
        let mut current = self.root_id;
        for link_id in path.links() {
            let link = self.links.get(link_id).ok_or_else(|| {
                Error::InvalidData(format!("media path references missing link {link_id:?}"))
            })?;
            if link.parent_id != current {
                return Err(Error::InvalidData(
                    "media path contains a disconnected placement link".into(),
                ));
            }
            current = link.media_id;
        }
        Ok(current)
    }

    /// Creates an unattached reusable media definition.
    ///
    /// # Errors
    ///
    /// Returns an error when its name is empty, time base is invalid, duration is negative, or an
    /// identifier overflows.
    pub fn create_media(
        &mut self,
        name: impl Into<String>,
        kind: MediaKind,
        time_base: Rational,
        duration: i64,
        origin: MediaOrigin,
    ) -> Result<MediaId> {
        let name = name.into();
        if name.trim().is_empty() {
            return Err(Error::InvalidData("media name cannot be empty".into()));
        }
        if time_base.numerator() <= 0 || duration < 0 {
            return Err(Error::InvalidData(
                "media time base must be positive and duration cannot be negative".into(),
            ));
        }
        let id = MediaId(self.next_media_id);
        self.next_media_id = self
            .next_media_id
            .checked_add(1)
            .ok_or_else(|| Error::InvalidData("media identifier overflows".into()))?;
        self.media.insert(
            id,
            MediaNode {
                id,
                name,
                kind,
                time_base,
                duration: Timestamp {
                    value: duration,
                    time_base,
                },
                origin,
                children: Vec::new(),
            },
        );
        Ok(id)
    }

    /// Places media in a parent's local timeline.
    ///
    /// # Errors
    ///
    /// Returns an error for missing nodes, duplicate/invalid aliases, inconsistent time bases,
    /// unequal source/timeline durations, invalid ranges, or a composition cycle.
    pub fn link_media(
        &mut self,
        parent_id: MediaId,
        media_id: MediaId,
        alias: impl Into<String>,
        source_range: TimeRange,
        timeline_range: TimeRange,
    ) -> Result<MediaLinkId> {
        let alias = alias.into();
        validate_alias(&alias)?;
        let parent = self
            .media
            .get(&parent_id)
            .ok_or_else(|| Error::InvalidData(format!("missing parent media {parent_id:?}")))?;
        let child = self
            .media
            .get(&media_id)
            .ok_or_else(|| Error::InvalidData(format!("missing child media {media_id:?}")))?;
        if timeline_range.start.time_base != parent.time_base
            || source_range.start.time_base != child.time_base
        {
            return Err(Error::InvalidData(
                "media link ranges use the wrong parent or child time base".into(),
            ));
        }
        TimeRange::new(source_range.start, source_range.end)?;
        TimeRange::new(timeline_range.start, timeline_range.end)?;
        if source_range.start.value < 0 || source_range.end.value > child.duration.value {
            return Err(Error::InvalidData(
                "media link source range lies outside the child duration".into(),
            ));
        }
        let source_duration = source_range
            .duration()?
            .rescale(parent.time_base, TimestampRounding::Exact)?;
        if source_duration.value != timeline_range.duration()?.value {
            return Err(Error::Unsupported(
                "initial media links cannot change playback speed".into(),
            ));
        }
        if parent.children.iter().any(|link_id| {
            self.links
                .get(link_id)
                .is_some_and(|link| link.alias == alias)
        }) {
            return Err(Error::InvalidData(format!(
                "media alias '{alias}' already exists in this local timeline"
            )));
        }
        if parent_id == media_id || self.reaches(media_id, parent_id) {
            return Err(Error::InvalidData(
                "media placement would create a composition cycle".into(),
            ));
        }
        let id = MediaLinkId(self.next_link_id);
        self.next_link_id = self
            .next_link_id
            .checked_add(1)
            .ok_or_else(|| Error::InvalidData("media-link identifier overflows".into()))?;
        self.links.insert(
            id,
            MediaLink {
                id,
                parent_id,
                media_id,
                alias,
                source_range,
                timeline_range,
            },
        );
        let parent = self
            .media
            .get_mut(&parent_id)
            .ok_or_else(|| Error::InvalidState("validated parent media disappeared".into()))?;
        parent.children.push(id);
        if timeline_range.end.value > parent.duration.value {
            parent.duration.value = timeline_range.end.value;
        }
        Ok(id)
    }

    /// Creates generated media and immediately links it into `parent_id`.
    ///
    /// # Errors
    ///
    /// Returns the same validation errors as [`Self::create_media`] and [`Self::link_media`].
    pub fn add_generated(
        &mut self,
        parent_id: MediaId,
        kind: MediaKind,
        alias: impl Into<String>,
        start: i64,
        duration: i64,
    ) -> Result<MediaLinkId> {
        if start < 0 || duration <= 0 {
            return Err(Error::InvalidData(
                "generated media start cannot be negative and duration must be positive".into(),
            ));
        }
        let alias = alias.into();
        let time_base = self
            .media(parent_id)
            .ok_or_else(|| Error::InvalidData(format!("missing parent media {parent_id:?}")))?
            .time_base;
        let media_id = self.create_media(
            alias.clone(),
            kind,
            time_base,
            duration,
            MediaOrigin::Generated,
        )?;
        let end = start
            .checked_add(duration)
            .ok_or_else(|| Error::InvalidData("generated media placement overflows".into()))?;
        self.link_media(
            parent_id,
            media_id,
            alias,
            time_range(0, duration, time_base)?,
            time_range(start, end, time_base)?,
        )
    }

    /// Returns child placements of the media reached by `path`.
    ///
    /// # Errors
    ///
    /// Returns an error for an invalid path or corrupted link reference.
    pub fn list(&self, path: &MediaPath) -> Result<Vec<MediaListing>> {
        let media_id = self.resolve_path(path)?;
        let media = self
            .media(media_id)
            .ok_or_else(|| Error::InvalidState("resolved media disappeared".into()))?;
        media
            .children()
            .iter()
            .map(|link_id| {
                let link = self
                    .links
                    .get(link_id)
                    .ok_or_else(|| Error::InvalidState("media child link disappeared".into()))?;
                let child = self
                    .media
                    .get(&link.media_id)
                    .ok_or_else(|| Error::InvalidState("linked child media disappeared".into()))?;
                Ok(MediaListing {
                    link_id: *link_id,
                    alias: link.alias.clone(),
                    kind: child.kind.clone(),
                    timeline_range: link.timeline_range,
                })
            })
            .collect()
    }

    /// Finds a child placement by alias or zero-based composition index.
    ///
    /// # Errors
    ///
    /// Returns an error for an invalid path or missing child selector.
    pub fn child(&self, path: &MediaPath, selector: &str) -> Result<MediaLinkId> {
        let media_id = self.resolve_path(path)?;
        let media = self
            .media(media_id)
            .ok_or_else(|| Error::InvalidState("resolved media disappeared".into()))?;
        if let Ok(index) = selector.parse::<usize>() {
            return media.children.get(index).copied().ok_or_else(|| {
                Error::InvalidData(format!("local media index {index} does not exist"))
            });
        }
        media
            .children
            .iter()
            .find_map(|link_id| {
                self.links
                    .get(link_id)
                    .filter(|link| link.alias == selector)
                    .map(|_| *link_id)
            })
            .ok_or_else(|| {
                Error::InvalidData(format!("local media alias '{selector}' does not exist"))
            })
    }

    /// Returns a slash-separated placement path.
    ///
    /// # Errors
    ///
    /// Returns an error when the path is invalid.
    pub fn display_path(&self, path: &MediaPath) -> Result<String> {
        self.resolve_path(path)?;
        if path.links().is_empty() {
            return Ok("/".into());
        }
        let aliases = path
            .links()
            .iter()
            .map(|link_id| {
                self.links
                    .get(link_id)
                    .map(|link| link.alias.as_str())
                    .ok_or_else(|| Error::InvalidState("media path link disappeared".into()))
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(format!("/{}", aliases.join("/")))
    }

    /// Trims the current placement's source and parent-local beginning.
    ///
    /// `value` is absolute in child frames unless `relative` is true.
    ///
    /// # Errors
    ///
    /// Returns an error for the root, invalid ranges, negative time, or inexact time-base mapping.
    pub fn trim_in(&mut self, path: &MediaPath, value: i64, relative: bool) -> Result<()> {
        let link_id = path.current_link().ok_or_else(|| {
            Error::Unsupported("the project root has no placement in-point".into())
        })?;
        let link = self
            .links
            .get(&link_id)
            .cloned()
            .ok_or_else(|| Error::InvalidData("current media link is missing".into()))?;
        let source_start = if relative {
            link.source_range
                .start
                .value
                .checked_add(value)
                .ok_or_else(|| Error::InvalidData("media in-point overflows".into()))?
        } else {
            value
        };
        if source_start < 0 || source_start >= link.source_range.end.value {
            return Err(Error::InvalidData(
                "media in-point must precede its out-point and cannot be negative".into(),
            ));
        }
        let delta = timestamp(
            source_start - link.source_range.start.value,
            link.source_range.start.time_base,
        )
        .rescale(
            link.timeline_range.start.time_base,
            TimestampRounding::Exact,
        )?;
        let timeline_start = link
            .timeline_range
            .start
            .value
            .checked_add(delta.value)
            .ok_or_else(|| Error::InvalidData("media timeline in-point overflows".into()))?;
        if timeline_start < 0 || timeline_start >= link.timeline_range.end.value {
            return Err(Error::InvalidData(
                "trimmed media placement has an invalid timeline range".into(),
            ));
        }
        let link = self
            .links
            .get_mut(&link_id)
            .ok_or_else(|| Error::InvalidState("current media link disappeared".into()))?;
        link.source_range.start.value = source_start;
        link.timeline_range.start.value = timeline_start;
        Ok(())
    }

    /// Trims the current placement's source and parent-local ending.
    ///
    /// `value` is absolute in child frames unless `relative` is true.
    ///
    /// # Errors
    ///
    /// Returns an error for the root, invalid ranges, or inexact time-base mapping.
    pub fn trim_out(&mut self, path: &MediaPath, value: i64, relative: bool) -> Result<()> {
        let link_id = path.current_link().ok_or_else(|| {
            Error::Unsupported("the project root has no placement out-point".into())
        })?;
        let link = self
            .links
            .get(&link_id)
            .cloned()
            .ok_or_else(|| Error::InvalidData("current media link is missing".into()))?;
        let source_end = if relative {
            link.source_range
                .end
                .value
                .checked_add(value)
                .ok_or_else(|| Error::InvalidData("media out-point overflows".into()))?
        } else {
            value
        };
        let child_duration = self
            .media(link.media_id)
            .ok_or_else(|| Error::InvalidState("linked media disappeared".into()))?
            .duration
            .value;
        if source_end <= link.source_range.start.value || source_end > child_duration {
            return Err(Error::InvalidData(
                "media out-point must follow its in-point and stay inside the source".into(),
            ));
        }
        let delta = timestamp(
            source_end - link.source_range.end.value,
            link.source_range.end.time_base,
        )
        .rescale(link.timeline_range.end.time_base, TimestampRounding::Exact)?;
        let timeline_end = link
            .timeline_range
            .end
            .value
            .checked_add(delta.value)
            .ok_or_else(|| Error::InvalidData("media timeline out-point overflows".into()))?;
        if timeline_end <= link.timeline_range.start.value {
            return Err(Error::InvalidData(
                "trimmed media placement has an invalid timeline range".into(),
            ));
        }
        let link = self
            .links
            .get_mut(&link_id)
            .ok_or_else(|| Error::InvalidState("current media link disappeared".into()))?;
        link.source_range.end.value = source_end;
        link.timeline_range.end.value = timeline_end;
        Ok(())
    }

    fn reaches(&self, start: MediaId, target: MediaId) -> bool {
        let mut pending = vec![start];
        let mut visited = std::collections::BTreeSet::new();
        while let Some(media_id) = pending.pop() {
            if media_id == target {
                return true;
            }
            if !visited.insert(media_id) {
                continue;
            }
            if let Some(media) = self.media.get(&media_id) {
                pending.extend(
                    media
                        .children
                        .iter()
                        .filter_map(|link_id| self.links.get(link_id).map(|link| link.media_id)),
                );
            }
        }
        false
    }
}

fn validate_alias(alias: &str) -> Result<()> {
    if alias.trim().is_empty()
        || alias.contains('/')
        || alias == "."
        || alias == ".."
        || alias.chars().any(char::is_control)
    {
        return Err(Error::InvalidData(format!(
            "'{alias}' is not a valid media-link alias"
        )));
    }
    Ok(())
}

fn timestamp(value: i64, time_base: Rational) -> Timestamp {
    Timestamp { value, time_base }
}

fn time_range(start: i64, end: i64, time_base: Rational) -> Result<TimeRange> {
    TimeRange::new(timestamp(start, time_base), timestamp(end, time_base))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> MediaProject {
        MediaProject::new("Film", Rational::new(1, 25).unwrap()).unwrap()
    }

    #[test]
    fn recursively_links_media_without_artificial_tracks() {
        let mut project = project();
        let clip = project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                0,
                100,
            )
            .unwrap();
        let mut clip_path = MediaPath::root();
        clip_path.push(clip);
        let clip_id = project.resolve_path(&clip_path).unwrap();
        let title = project
            .add_generated(clip_id, MediaKind::new("text").unwrap(), "Title", 10, 20)
            .unwrap();
        clip_path.push(title);

        assert_eq!(project.display_path(&clip_path).unwrap(), "/Clip0/Title");
        assert_eq!(project.list(&MediaPath::root()).unwrap()[0].alias, "Clip0");
    }

    #[test]
    fn rejects_composition_cycles() {
        let mut project = project();
        let time_base = Rational::new(1, 25).unwrap();
        let first = project
            .create_media(
                "First",
                MediaKind::new("group").unwrap(),
                time_base,
                10,
                MediaOrigin::Generated,
            )
            .unwrap();
        let second = project
            .create_media(
                "Second",
                MediaKind::new("group").unwrap(),
                time_base,
                10,
                MediaOrigin::Generated,
            )
            .unwrap();
        project
            .link_media(
                first,
                second,
                "Second",
                time_range(0, 10, time_base).unwrap(),
                time_range(0, 10, time_base).unwrap(),
            )
            .unwrap();
        assert!(
            project
                .link_media(
                    second,
                    first,
                    "First",
                    time_range(0, 10, time_base).unwrap(),
                    time_range(0, 10, time_base).unwrap(),
                )
                .is_err()
        );
    }

    #[test]
    fn trims_a_placement_without_mutating_the_reusable_media() {
        let mut project = project();
        let link_id = project
            .add_generated(
                project.root_id(),
                MediaKind::new("video").unwrap(),
                "Clip0",
                5,
                100,
            )
            .unwrap();
        let mut path = MediaPath::root();
        path.push(link_id);
        project.trim_in(&path, 10, true).unwrap();
        project.trim_out(&path, -5, true).unwrap();

        let link = project.link(link_id).unwrap();
        assert_eq!(
            (link.source_range.start.value, link.source_range.end.value),
            (10, 95)
        );
        assert_eq!(
            (
                link.timeline_range.start.value,
                link.timeline_range.end.value
            ),
            (15, 100)
        );
        assert_eq!(project.media(link.media_id).unwrap().duration.value, 100);
    }
}
