[package]
name = "mmrecode-playback"
description = "Media timeline and playback clock primitives for MMRecode"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mmrecode-aac.workspace = true
mmrecode-core.workspace = true
mmrecode-h264.workspace = true
mmrecode-isobmff.workspace = true
mmrecode-mpegaudio.workspace = true
mmrecode-mpeg2.workspace = true
mmrecode-mpegts.workspace = true

[lints]
workspace = true
